# Project information
site_name: Gluu Server Enterprise Edition 4.1 Docs
site_description: Documentation for Gluu Server Edition Edition

# Copyright
copyright: Copyright &copy; 2020, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-ee-prod
repo_url: https://github.com/GluuFederation/docs-ee-prod/
edit_uri: edit/4.1/docs/source

# Configuration
theme:
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '4.1'

# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '4.1': 'https://gluu.org/docs/ee/4.1/'
- ' ': 'https:/gluu.org/docs'
- ' ': 'https:/gluu.org/docs'
- 'Introduction': 'index.md'
- 'Whats new in v4': '4.x-intro.md'
- 'Installation':
  - 'Packaging the installer': 'installation/package.md'
  - 'Setup': 'installation/kubernetes.md'
- 'Technical Reference':
  - 'Image References': 'reference/index.md'
  - 'Configuration Keys': 'reference/configs.md'
- 'Operation Guide':
  - 'Preparing the Server': 'operation/server.md'
  - 'Managing the Vault': 'operation/vault.md'
  - 'Managing Logs': 'operation/logging.md'
  - 'Customizing oxAuth': 'operation/custom-oxauth.md'
  - 'Customizing oxTrust': 'operation/custom-oxtrust.md'
  - 'Custom LDAP Schema': 'operation/custom-schema.md'
  - 'Upgrading': 'operation/upgrade.md'
  - 'oxAuth Key Rotation': 'operation/key-rotation.md'
  - 'Cache Refresh Rotation': 'operation/cr-rotate.md'
  - 'oxTrust API': 'operation/oxtrust-api.md'
